import { Labels } from 'declarations/types.d'

export default {
  alert_invalidStep1: 'Last opp noe filer før du fortsette',
  alert_invalidStep2: 'Velg noe sider/bilder før du fortsette',
  button_back: 'Tilbake',
  button_forward: 'Neste',
  button_downloadAll: 'Last ned alle',
  button_addAll: 'Legg til alle',
  help_sizeSliderTooltip: 'Velg størrelse',
  label_download: 'Last ned',
  label_content: 'Innhold',
  label_home: 'Botid',
  label_work: 'Arbeid',
  label_sick: 'Sykdom',
  label_other: 'Annet',
  label_documentBox: 'Dokumentboks',
  label_images: 'Bilder',
  label_startAgain: 'Start på nytt',
  label_watermark: 'Vannmerke',
  loading_loadingPDF: 'Laster ny PDF...',
  loading_generatingPDF: 'Genererer ny PDF...',
  modal_empty_title: 'Tøm PDF',
  modal_empty_text: 'Du har ikke valgt dokumenter og sider for generering av ny PDF',
  modal_cancel: 'Avbryt',
  modal_ok: 'Ok',
  modal_yes: 'Ja, generere',
  modal_valid_title: 'Generer ny PDF',
  modal_valid_text: 'Er du sikker på du vil generere ny PDF nå?',
  placeholder_text: 'Skriv tekst her, deretter dra siden til dokumentboks',
  placeholder_watermark: 'Vannmerke',
  step_1: 'Velg filer',
  step_2: 'Rediger PDFs',
  step_3: 'Genererer PDFs',
  title_fileUpload: 'Last opp filer',
  title_specials: 'Lage nytt brev'
} as Labels
