export const API_CALL_REJECTED = 'API/CALL/REJECTED'

export const SERVER_INTERNAL_ERROR = 'SERVER/INTERNAL/ERROR'
export const SERVER_UNAUTHORIZED_ERROR = 'SERVER/UNAUTHORIZED/ERROR'

export const UI_TOGGLE_HIGHCONTRAST = 'UI/TOGGLE/HIGHCONSTRAST'
