import AlertStripe, { AlertStripeAdvarsel, AlertStripeFeil, AlertStripeInfo, AlertStripeSuksess } from 'nav-frontend-alertstriper'
import { BekreftCheckboksPanel, Checkbox, CheckboksPanel, CheckboksPanelGruppe, Fieldset, Input, Radio, RadioPanel, RadioPanelGruppe, Select, SkjemaGruppe, Textarea, TextareaControlled } from 'nav-frontend-skjema'
import Chevron from 'nav-frontend-chevron'
import Ekspanderbartpanel, { EkspanderbartpanelBase } from 'nav-frontend-ekspanderbartpanel'
import EtikettBase, { EtikettAdvarsel, EtikettFokus, EtikettInfo, EtikettSuksess } from 'nav-frontend-etiketter'
import { Container, Row, Column } from 'nav-frontend-grid'
import Hjelpetekst from 'nav-frontend-hjelpetekst'
import { Hamburgerknapp, Lukknapp, Menyknapp, Nesteknapp, Systemerknapp, Søkeknapp, Tilbakeknapp } from 'nav-frontend-ikonknapper'
import Ikon from 'nav-frontend-ikoner-assets'
import KnappBase, { Knapp, Hovedknapp, Flatknapp, Fareknapp } from 'nav-frontend-knapper'
import Lenke from 'nav-frontend-lenker'
import Lenkepanel, { LenkepanelBase } from 'nav-frontend-lenkepanel'
import Lesmerpanel from 'nav-frontend-lesmerpanel'
import Modal from 'nav-frontend-modal'
import PanelBase, { Panel } from 'nav-frontend-paneler'
import Popover from 'nav-frontend-popover'
import Snakkeboble from 'nav-frontend-snakkeboble'
import Spinner from 'nav-frontend-spinner'
import Stegindikator from 'nav-frontend-stegindikator'
import Tabs from 'nav-frontend-tabs'
import Tekstomrade from 'nav-frontend-tekstomrade'
import { ToggleGruppe, ToggleKnapp } from 'nav-frontend-toggle'
import { Sidetittel, Innholdstittel, Systemtittel, Undertittel, Element, Normaltekst, EtikettLiten, Undertekst, UndertekstBold, Ingress } from 'nav-frontend-typografi'
import Veileder from 'nav-frontend-veileder'
import Veilederpanel from 'nav-frontend-veilederpanel'

AlertStripe.displayName = 'AlertStripe'
AlertStripeAdvarsel.displayName = 'AlertStripeAdvarsel'
AlertStripeFeil.displayName = 'AlertStripeFeil'
AlertStripeInfo.displayName = 'AlertStripeInfo'
AlertStripeSuksess.displayName = 'AlertStripeSuksess'
BekreftCheckboksPanel.displayName = 'BekreftCheckboksPanel'
Checkbox.displayName = 'Checkbox'
CheckboksPanel.displayName = 'CheckboksPanel'
CheckboksPanelGruppe.displayName = 'CheckboksPanelGruppe'
Chevron.displayName = 'Chevron'
Container.displayName = 'Container'
Column.displayName = 'Column'
Ekspanderbartpanel.displayName = 'Ekspanderbartpanel'
EkspanderbartpanelBase.displayName = 'EkspanderbartpanelBase'
Element.displayName = 'Element'
EtikettBase.displayName = 'EtikettBase'
EtikettAdvarsel.displayName = 'EtikettAdvarsel'
EtikettFokus.displayName = 'EtikettFokus'
EtikettInfo.displayName = 'EtikettInfo'
EtikettSuksess.displayName = 'EtikettSuksess'
EtikettLiten.displayName = 'EtikettLiten'
Fareknapp.displayName = 'Fareknapp'
Fieldset.displayName = 'Fieldset'
Flatknapp.displayName = 'Flatknapp'
Hamburgerknapp.displayName = 'Hamburgerknapp'
Hjelpetekst.displayName = 'Hjelpetekst'
Hovedknapp.displayName = 'Hovedknapp'
Ikon.displayName = 'Ikon'
Ingress.displayName = 'Ingress'
Innholdstittel.displayName = 'Innholdstittel'
Input.displayName = 'Input'
Knapp.displayName = 'Knapp'
KnappBase.displayName = 'KnappBase'
Lenke.displayName = 'Lenke'
Lenkepanel.displayName = 'Lenkepanel'
LenkepanelBase.displayName = 'LenkepanelBase'
Lesmerpanel.displayName = 'Lesmerpanel'
Lukknapp.displayName = 'Lukknapp'
Modal.displayName = 'Modal'
Menyknapp.displayName = 'Menyknapp'
Nesteknapp.displayName = 'Nesteknapp'
Normaltekst.displayName = 'Normaltekst'
Panel.displayName = 'Panel'
PanelBase.displayName = 'PanelBase'
Popover.displayName = 'Popover'
Radio.displayName = 'Radio'
RadioPanel.displayName = 'RadioPanel'
RadioPanelGruppe.displayName = 'RadioPanelGruppe'
Row.displayName = 'Row'
Select.displayName = 'Select'
Select.displayName = 'Select'
SkjemaGruppe.displayName = 'SkjemaGruppe'
Snakkeboble.displayName = 'Snakkeboble'
Spinner.displayName = 'Spinner'
Stegindikator.displayName = 'Stegindikator'
Systemtittel.displayName = 'Systemtittel'
Systemerknapp.displayName = 'Systemerknapp'
Søkeknapp.displayName = 'Søkeknapp'
Tabs.displayName = 'Tabs'
Tekstomrade.displayName = 'Tekstomrade'
Textarea.displayName = 'Textarea'
TextareaControlled.displayName = 'TextareaControlled'
Tilbakeknapp.displayName = 'Tilbakeknapp'
ToggleGruppe.displayName = 'ToggleGruppe'
ToggleKnapp.displayName = 'ToggleKnapp'
Undertittel.displayName = 'Undertittel'
Undertekst.displayName = 'Undertekst'
UndertekstBold.displayName = 'UndertekstBold'
Veileder.displayName = 'Veileder'
Veilederpanel.displayName = 'Veilederpanel'

export {
  AlertStripe, AlertStripeAdvarsel, AlertStripeFeil, AlertStripeInfo, AlertStripeSuksess,
  BekreftCheckboksPanel,
  Checkbox, CheckboksPanel, CheckboksPanelGruppe, Chevron, Container, Column,
  Ekspanderbartpanel, EkspanderbartpanelBase, Element, EtikettBase, EtikettAdvarsel, EtikettFokus, EtikettInfo, EtikettSuksess, EtikettLiten,
  Fareknapp, Fieldset, Flatknapp,
  Hamburgerknapp, Hjelpetekst, Hovedknapp,
  Ikon, Ingress, Innholdstittel, Input,
  Knapp, KnappBase,
  Lenke, Lenkepanel, LenkepanelBase, Lesmerpanel, Lukknapp,
  Modal, Menyknapp,
  Nesteknapp, Normaltekst,
  Panel, PanelBase, Popover,
  Radio, RadioPanel, RadioPanelGruppe, Row,
  Select, Sidetittel, SkjemaGruppe, Snakkeboble, Spinner, Stegindikator, Systemtittel, Systemerknapp, Søkeknapp,
  Tabs, Tekstomrade, Textarea, TextareaControlled, Tilbakeknapp, ToggleGruppe, ToggleKnapp,
  Undertittel, Undertekst, UndertekstBold,
  Veileder, Veilederpanel
}
